### ISSUE TITLE
MIssing sponge functions

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/sponges#1]
- [ ] Keccak variants: generic keccak-p and other sizes for keccak-f (200, 400, 800)

**Comment by quininer** [comment]
Blake2 permutation is also common, and it is used by [blabla](https://github.com/veorq/blabla) and [mem-aead](https://github.com/MEM-AEAD/mem-aead).

**Comment by newpavlov** [comment]
AFAIK BLAKE2 permutations are not considered sponge functions. (i.e. they are not used in sponge constuctions)

**Comment by quininer** [comment]
MEM-AEAD MRS is a sponge constuctions.
NORX is a sponge constuctions that uses a permutation similar to BLAKE2.

 In fact it is just a permutation, there is no difference between sponge functions.

**Comment by dustinvonsandwich** [comment]
The lib you have labeled here does not appear to be a sponge, rather it seems to be the KECCAK[f] permutation. A sponge has a state that absorbs data in certain predfined fashion defined by the KECCAK team and NIST. 

Check out the KECCAK teams official readable sponge implementation:

https://github.com/XKCP/XKCP/blob/master/Standalone/CompactFIPS202/C/Keccak-readable-and-compact.c

Would be happy to work on this with you but I dont know Rust (yet).

**Comment by newpavlov** [comment]
@dustinvonsandwich 
The naming was briefly discussed in this [issue](https://github.com/RustCrypto/sponges/issues/2). SHA-3 hash functions (including XOFs) are implemented in the `sha3` (it uses `keccak` under the hood), which is part of [RustCrypto/hashes](https://github.com/RustCrypto/hashes) repository. We don't have a generic implementation of the sponge framework at the moment.
