### ISSUE TITLE
Clarify `sponge function`

### ISSUE THREAD

**Issue by quininer** [RustCrypto/sponges#2]
I don't quite understand what `sponge function` means in this repo. It looks like a `one-way permutation`, not a `construction`/`mode of operation`?

**Comment by newpavlov** [comment]
The more precise wording will be "permutations designed for uses in sponge constructions". Though I am thinking about renaming this repository to just "keccak". I will be happy to hear your opinion on this matter.

**Comment by bwesterb** [comment]
> I don't quite understand what `sponge function` means in this repo. It looks like a `one-way permutation`, not a `construction`/`mode of operation`?

By definition a permutation is invertible.  Perhaps you mean with "one-way permutation" that `keccak-f` is computationally hard to invert.  This is not the case at all for `keccak-f`: the inverse is [easy to compute](https://github.com/KeccakTeam/KeccakTools/blob/e5b7356bbbaa5a8f823ba517c7108b395d05f35a/Sources/Keccak-f.cpp).  The security of the sponge construction relies on the hidden state.

**Comment by quininer** [comment]
> By definition a permutation is invertible. Perhaps you mean with "one-way permutation" that keccak-f is computationally hard to invert.

I may have accidentally hinted that `keccak-f` is hard to invert, but this is not my intention. `one-way permutation` only means that we don't need to provide an inverse function.

>  This is not the case at all for keccak-f: the inverse is easy to compute. The security of the sponge construction relies on the hidden state.

This is actually a common design. The permutation functions of `blake2`, `ascon`, and `gimli` are actually invertible, and even some aead constructs (mem-aead opp) use this feature.
