### ISSUE TITLE
keccak: drop old CC0-1.0 LICENSE file

### ISSUE THREAD

**Issue by decathorpe** [RustCrypto/sponges#29]
It looks like when the keccak crate was relicensed, the old LICENSE file was not removed. For some baffling reason (???), the file was also not included in published crates, but with version 0.1.3, the .crate file published and redistributed on crates.io includes the LICENSE file again.

**Comment by tarcieri** [comment]
Fixed in [2d2be35](https://github.com/RustCrypto/sponges/commit/2d2be3511ab9810d0c34632036255067e085d36b)

**Comment by decathorpe** [comment]
Thanks!
