### ISSUE TITLE
Relicense from CC0 to  MIT/Apache-2.0?

### ISSUE THREAD

**Issue by repi** [RustCrypto/sponges#5]
Ran into that this crate is licensed under the not so common CC0 license, which Open Software Institute [does not recommend](https://opensource.org/faq#cc-zero), so I/we generally try to avoid it as well.

Would it be possible to re-license this crate under the standard Rust `MIT OR Apache-2.0`? Like all the other RustCrypto crates? 

Looks like @newpavlov have been the only contributor to this crate so far which would make it easy to change.

**Comment by newpavlov** [comment]
The code in this crate is based on `tiny-keccak`, so the license got inherited from it. I guess there shouldn't be no problems in re-licensing it under `MIT OR Apache-2.0`.

**Comment by repi** [comment]
Thanks, that would be sweet!
